#pragma once

#include "./alphabetHistogram/op.cuh"
#include "./alphabetHistogram/op.hpp"
#include "./conv2d/op.cuh"
#include "./conv2d/op.hpp"
#include "./cvtRGBtoGray/op.cuh"
#include "./cvtRGBtoGray/op.hpp"
#include "./matmul/op.cuh"
#include "./matmul/op.hpp"
#include "./prefixSum/op.cuh"
#include "./prefixSum/op.hpp"
#include "./reduction/op.cuh"
#include "./reduction/op.hpp"
#include "./vecAdd/op.cuh"
#include "./vecAdd/op.hpp"