set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

# Force old ABI off
set(ENV{CXXFLAGS} "$ENV{CXXFLAGS} -D_GLIBCXX_USE_CXX11_ABI=0")
set(ENV{CFLAGS} "$ENV{CFLAGS} -D_GLIBCXX_USE_CXX11_ABI=0")