OpTest:
  VecAdd:
    - nElems: 32
    - nElems: 1024
    - nElems: 2048
    - nElems: 1048576  # 1024*1024
    - nElems: 8388608  # 1024*1024
  Conv2D:
    - inputHeight: 32
      inputWidth: 32
      kernelSize: 3
  AlphabetHistogram:
    - nInputs: 256
      divider: 4
    - nInputs: 2048
      divider: 4
  MulReduction:
    - nInputs: 32
  PrefixSum:
    - nInputs: 32
    - nInputs: 64
    - nInputs: 128