OpTest:
  Conv2D:
    - inputHeight: 32
      inputWidth: 32
      kernelSize: 3
  AlphabetHistogram:
    - nInputs: 256
      divider: 4
    - nInputs: 2048
      divider: 4
  MulReduction:
    - nInputs: 32
    # # [NOTE] The following calculation results would be wrong?
    # - nInputs: 64
    # - nInputs: 128
    # - nInputs: 512